moderation_api:
  moderation_api_enabled:
    type: boolean
    default: false
    client: true
  moderation_api_flagging_behavior:
    default: "Flag post"
    type: enum
    choices:
      - Queue for review
      - Flag post
      - Block post
      - Nothing

  moderation_api_block_message:
    default: "Your post has been blocked by our moderation system."
  moderation_api_notify_on_post_queue:
    default: true
  moderation_api_check_private_message:
    default: false
    client: true
  moderation_api_skip_groups:
    default: []
    type: group_list
    allow_any: false
    refresh: true

  moderation_api_skip_categories:
    type: category_list
    default: []
    allow_any: false
    refresh: true

  moderation_api_key:
    default: ""

  aliyun_access_key_id:
    default: ""

  aliyun_access_key_secret:
    default: ""

  aliyun_region:
    default: "cn-shanghai"

  aliyun_risk_level_allow_list:
    default: "none,low"
    type: list
    list_type: compact
    choices: # 使用 YAML 数组语法
    - "none"
    - "low"
    - "medium"
    - "high"
    client: false
    description: "允许通过的风险等级（逗号分隔）"

  moderation_api_webhook_signing_secret:
    default: ''
    client: false